# Site settings
title: My Portfolio
email: aranshinge@ucdavis.edu
description: > My profile # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ashishranshinge.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: AshishRanshinge

# Build settings
markdown: kramdown
