baseURL = "https://ashishranshinge.github.io/"
languageCode = "en-us"
title = "Ashish Ranshinge"
theme = "hugo-resume"

[params]
    firstName = "Ashish"
    lastName = "Ranshinge"
    address = "San Francisco, CA"
    phone = "1-479-407-8393"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/TechChat.png"
    email = "aranshinge@ucdavis.edu"
    description = "Business Analysts with prior work experience in Business Intelligence domain."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/ashishranshinge/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/AshishRanshinge"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/ashish.ranshinge"

[params.google.analytics]
    trackerID = "XX-123446-01"
